### ISSUE TITLE
Problem when no client macs available

### ISSUE THREAD

**Issue by Mark-Booth** [meermanr/LightwaveRF#1]
Trying to get this project to work for me, I discovered a problem with running out of client slots.

The Lightwave Link only supports 12 clients connecting to it, and if there are already 12 devices connected, then the `!F*p` commands to register are _silently_ ignored.

I eventually noticed the `u'macs': 12` in the `hubCall` response which prompted me de-authorise all existing devices (most of them haven't been used for a while, and this explains why my new phone has always been stuck in 'remote' mode, it couldn't make a direct connection, so always went out to the web for it's connection). 

I have a hacky solution to this problem in my test instance, but I'll issue a pull request when I've got a properly engineered solution. Thanks for all the work you put into this.

**Comment by meermanr** [comment]
Thanks for reporting this, I look forward to your pull request!

Robert
